### ISSUE TITLE
Doesn't work on http

### ISSUE THREAD

**Issue by lichenophile** [muckelba/dynamic-lights-homeassistant#1]
It seems that the payload is unable to be sent due to spotify using https and my HA instance only using http
![image](https://github.com/user-attachments/assets/45061cbf-9697-4604-9f33-2fbacefdba5c)
Unfortunately I don't have https set up to test with it instead, but let me know if you want more detailed logs

Cool concept btw. I've been using https://github.com/ericmatte/ad-media-lights-sync 
But relying on my media_player updating, can be slow at times due to the spotify integrations update interval
It does, however, support sampling more than one colour and various modes for how it samples them, which is nice

**Comment by muckelba** [comment]
Hey, thanks for the heads up, i actually did not test http connections as my home assistant instance has a valid SSL certificate. To be honest I dont know if that issue is fixable as that's a limitation from Spotify/Chromium. I'll have a look later this week. ( I hope at least, if i forget it, please ping me again :))

**Comment by muckelba** [comment]
Sorry, I'm not able to find a solution for this. Allowing mixed content is beyond the scope of spicetify and making a request to an invalid (selfsigned) SSL endpoint is not possible on the client side it seems. If you know any other workaround, let me know.

**Comment by muckelba** [comment]
SSL isn't too hard. especially with duck DNS and DNS verification. no need to expose your HA instance to the internet :) 

I'll close this issue for now.
